### ISSUE TITLE
Backup via ssh

### ISSUE THREAD

**Issue by zygzagZ** [ameer1234567890/OnlineNandroid#43]
Hello.
I have edited this script so that it sends backup to server via ssh, here is a patch: http://pastebin.com/Y1E2rhWZ
It still needs work over it, but it works and i guess it's something to start with in terms of "cloud backup". Few additions need to be deleted as they are not needed.
The reason i made this is that i always only have like 1 gb of space left on my device so i decided to send backup on-the-fly to server so it doesn't need free space at all. 
Performance wise: 
For me creating and uploading full backup takes around ~30-40 minutes (nexus 4)
Thank you for creating and sharing onandroid.

**Comment by ameer1234567890** [comment]
Thank you for this. In my opinion, it would be best to have this functionality as an app or a separate script which invokes Online Nandroid.
