### ISSUE TITLE
Samsung Galaxy III  

### ISSUE THREAD

**Issue by rigeback** [ameer1234567890/OnlineNandroid#47]
Hi, I have a problem with a partition table on a  S3 GT-i9300 bought in Italy.
The phone will only boot into download mode, when flashing original firmware with Odin including the PIT Odin stops at reparation. 
I would like to try one of your flash files but not sure which one will work??
Thanks

**Comment by ameer1234567890** [comment]
This isn't an issue with Online Nandroid. It is rather a device firmware issue. Ask at XDA.
